# name: Build and deploy Node.js app to Azure Web App - web-app-b032b0a2

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18.x"

#       - name: npm install, build, and test
#         run: |
#           npm install
#           npm run build --if-present

#       - name: Zip artifact for deployment
#         run: zip release.zip ./* -r

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: node-app
#           path: release.zip

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: "Production"
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#     permissions:
#       id-token: write #This is required for requesting the JWT

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: node-app

#       - name: Unzip artifact for deployment
#         run: unzip release.zip

#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE47F0447D27483DBE212F1EC9A9BFDC }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C444928DC467474093C7064086902374 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E5492259BAB46A2832E7E7A6669874B }}

#       - name: "Deploy to Azure Web App"
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: "web-app-b032b0a2"
#           slot-name: "Production"
#           package: .


name: Build and deploy Node.js app as a Docker container to Azure Web App - web-app-b032b0a2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/web-app-b032b0a2:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/web-app-b032b0a2:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE47F0447D27483DBE212F1EC9A9BFDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C444928DC467474093C7064086902374 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E5492259BAB46A2832E7E7A6669874B }}

      - name: Deploy Docker container to Azure Web App
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: "web-app-b032b0a2"
          images: "${{ secrets.DOCKER_HUB_USERNAME }}/web-app-b032b0a2:${{ github.sha }}"
